### ISSUE TITLE
add bower install support

### ISSUE THREAD

**Issue by kongaraju** [eligrey/canvas-toBlob.js#6]

**Comment by nicgirault** [comment]
:+1:

**Comment by frekele** [comment]
:+1:

**Comment by frekele** [comment]
I registered with the 'canvas-to-Blob.js' name for this repository 'https://github.com/eligrey/canvas-toBlob.js' in bower.herokuapp.com.

"canvas-to-Blob.js": "master",
 "file-saver": "master",
 "blob": "master",

:v: :smiley:

**Comment by frekele** [comment]
I registered with the **'canvas-to-Blob.js'** name for this repository 'https://github.com/eligrey/canvas-toBlob.js' in https://bower.herokuapp.com.

"canvas-to-Blob.js": "master",
 "file-saver": "master",
 "blob": "master",

:v: :smiley:

**Comment by evghenin** [comment]
Current package configuration generate error while running grunt or gulp compilation because of incorrectly file name: "_originalSource": "canvas-to-Blob.js".

Should be "_originalSource": "canvas-toBlob.js".

**Comment by pardo-bsso** [comment]
hey @frekele , could you please re-register it with the right _originalSource ? 
Thanks!
